### ISSUE TITLE
Homologar o alerjmobile para servidor SGUS de produção

### ISSUE THREAD

**Issue by BMasquio** [alerj/alerjmobile#4]
- 1. Colocar o alerjmobile em homologação (alv42) 
- 2. Abrir chamado para criar certificado (alerjmobilehom.alerj.rj.gov.br ou apiportalhom.alerj.rj.gov.br)
- 3. Ver qual a máquina que tem o banco de dados do SGUS de produção para conectar e qual o usuário de banco que usamos
- 4. Mudar o .env do alerjmobile de homologação (alv42) para os endereços do banco de dados do SGUS de produção
- 5. Testar as apis de permissões e login usando o postman

Exemplo de URLs para testar:

- https://alerjmobilehom.alerj.rj.gov.br/api/v1.0/ldap/0IYFFiMHuUr1sYo6wEtjUsJQ7Zicg33SMuvtrFk9yEgwrORmblNSMdpTH0ZTRKX2BhADIusjXHInHW3cspyosOoNrbd5jObK5Uoh/login

- https://alerjmobilehom.alerj.rj.gov.br/api/v1.0/ldap/d6fFGg5h4jui1k5loFG3p7d6fg5h4j3kDS8HJ/user

- http://alerjmobilehom.alerj.rj.gov.br/api/v1.0/adm-user/K7k8H95loFpTH0ZTRKX2BhADIusjXHInHW3cspyosOoNrbd5jOG3pd61F4d6fg584Gg5h4DSjui1k/permissions

**Comment by orlandovinicius1987** [comment]
- [ ] Colocar o alerjmobile em homologação (alv42)
- [ ] Abrir chamado para criar certificado (alerjmobilehom.alerj.rj.gov.br ou apiportalhom.alerj.rj.gov.br)
- [ ] Ver qual a máquina que tem o banco de dados do SGUS de produção para conectar e qual o usuário de banco que usamos
- [ ] Mudar o .env do alerjmobile de homologação (alv42) para os endereços do banco de dados do SGUS de produção
- [ ] Testar as apis de permissões e login usando o postman

**Comment by BMasquio** [comment]
Feito
